### ISSUE TITLE
referral system smart contracts

### ISSUE THREAD

**Issue by ororopickpocket** [DistributedCollective/Sovryn-smart-contracts#114]
It should work the following way:
when the user makes his first trade/borrowing, he passes an affiliate address to the smart contract. every time the user makes a trade, he pays some trading fees to the protocol. if he's got a referrer set, the referrer earns 20% of the fees.

* add mapping to the storage, making sure that existing storage structure does not change
* (only) on first trade users should be able to set referrer
* referrer cannot be changed once set
* users cannot be self referrers

**Comment by tjcloa** [comment]
moved to Referral system v2 #203
