### ISSUE TITLE
Delegation of Voting Power from the SOV under Vesting Contract is leaving 1 out of N vesting positions out

### ISSUE THREAD

**Issue by jjmr007** [DistributedCollective/Sovryn-smart-contracts#164]
If a user decides to delegate his voting power procedent from their SOV tokens locked under N vesting positions under the vesting contract, instead of transfering all the voting power of all N vesting positions, the voting power of 1 out of these N positions is left out of the delegation.

A user who made this observation create this document:

[Bitocracy_issues_3.pdf](https://github.com/DistributedCollective/Sovryn-smart-contracts/files/6084334/Bitocracy_issues_3.pdf)

**Comment by ororopickpocket** [comment]
this is a knwon issue which has already been addressed on the new vesting logic version
