### ISSUE TITLE
A User Lost Money on a BTC-Long Position even when the Closing Price was Higher than the Opening One

### ISSUE THREAD

**Issue by jjmr007** [DistributedCollective/Sovryn-smart-contracts#176]
A user open a 4x long position giving as collateral 0.009 rBTC, in [this transaction](https://explorer.rsk.co/tx/0x2bb96cf744683eef420f822e3a9ef70281a11aa2425cbd027b0e41279d5dc4f0)

But even when the position was opened as 4x with a collateral of 0.009 ... the position value was 
0.0221846498777346 BTC instead of being (approximately) 0.036 BTC.

Also the opening price (according the data of his loanId: 0x874d7f200f98e36ca33e9f1face4ebaf5ea7ce8d77641bb8424d310a4001b8c7) was
54,846.745887214454382336 $ per Bitcoin

He then closed the position with [this transaction](https://explorer.rsk.co/tx/0xe51cf4bc8fe331c099765ccb82b2f27438dc26f26545bd395b1ba98ff2eafef5)
which splitted the position assets into 0.006822713996262752 rBTC (given back to his wallet) and 0.015361935881471924 rBTC  to pay the loan, which end to be
858.455039713636341763 $ ... which seems to mean that the closing price was: 55.881,9569579 $ per BTC (higher than the opening price)

Question:  Why this user lost money? 

It seems we have (again) a Nx position where N is lower that the expected leverage (4 in this case).
Which is some how (not exactly) a similar case like [this one](https://github.com/DistributedCollective/Sovryn-smart-contracts/issues/125)

**Comment by ororopickpocket** [comment]
i looked it up on the admin panel, which you should do as well, julio.
you can search in the closed positions by loan ID.

There you see that the position size in the beginning was 0.3413630
Then he got partially liquidated.
Then he closed the remaining loan.

Because of the liquidation, it's no wonder he closed with a loss.

**Comment by jjmr007** [comment]
thank you very much for the clarification. Closing the issue now.
