### ISSUE TITLE
Governance Issue: `withdrawTokens` function succeed, but no transfer of tokens was performed

### ISSUE THREAD

**Issue by jjmr007** [DistributedCollective/Sovryn-smart-contracts#178]
A user did the following tx:

https://explorer.rsk.co/tx/0xb7e75a895a65b2ff50617eaec206ca0961ad74a925ab2efc69b2b9efd296fc2c?__ctab=Transaction

But no `TokensWithdrawn` event was emitted

User: `0x3B179Bd3B312050892E54d323c354f8787Fb2814`
the specific `vestingLogic` contract was: `0x9308305F7a16Edb124400BF8Fe3b4c0cAa18A095`

My main concern is verify that the user's tokens are not lost, and verify that there is no bug in these contracts
In second place: where did this user's tokens go?

**Comment by jameshowlett977** [comment]
Fixed in SIP-0016
