### ISSUE TITLE
Tests to make the Code Coverage reach 90%+

### ISSUE THREAD

**Issue by powerhousefrank** [DistributedCollective/Sovryn-smart-contracts#196]
Currently, the code coverage is at around 74%.

An effort has to be taken to make it reach around 90%+

Current Code Coverage: https://coveralls.io/github/DistributedCollective/Sovryn-smart-contracts/

**Comment by smbsp** [comment]
Was able to successfully run the code coverage. Had an insightful session with @tjcloa to understand the process this week. Will be focusing on the Vesting code coverage first alongside working on the Vesting Automation Contract coding.

21-05-2021: Set up and played with Tenderly account. Had a small session with @powerhousefrank to understand the utilities of the tool.

**Comment by smbsp** [comment]
Covered /mixins, overall coverage is 80%

**Comment by smbsp** [comment]
Completed test coverage for token and multisig modules: https://github.com/DistributedCollective/Sovryn-smart-contracts/commit/60e17de0f0054b31e1ac83fee94637b0133be572
Code Coverage ~ 88%. 
With Vesting and ExternalSwaps test cases, added in separate repositories (part of other tasks), the code coverage most certainly will be greater than 90%.

**Comment by powerhousefrank** [comment]
Please create the PR and link it to this issue. If not completely ready, maybe make it draft PR @smbsp

**Comment by smbsp** [comment]
> Please create the PR and link it to this issue. If not completely ready, maybe make it draft PR @smbsp

I have created a separate branch for this here: https://github.com/DistributedCollective/Sovryn-smart-contracts/tree/solidity-test-coverage . Currently working on PriceFeeds. Once that is done I will raise the PR.
