### ISSUE TITLE
add pausable to all logic contracts

### ISSUE THREAD

**Issue by tjcloa** [DistributedCollective/Sovryn-smart-contracts#210]
**upd: reinstantiated**
needs to be done ASAP to set multisig as the pauser before ownership of the contracts transferred to governance which is ready and waiting for this issue to be resolved 
**upd: postponed, needs longer discussion**
emergency system to pause every single module/logic
we also need one big red 'button' which will pause sovryn
this needs to be thoroughly tested
**UPD from @computerphysicslab** 
"It'd be useful to be able to declare a sort-of contract-level modifier, that allows to inject code that executes on every call received by the contract, and executes based on raw msg data, signature, etc. This allows to provide a global behaviour to the contract, without needing to manually add a modifier to every external function, which is error-prone if one is forgotten."

    https://github.com/ethereum/solidity/issues/3864

It seems to me that a contract-level pausable modifier is already implemented in our codebase at:

    https://github.com/DistributedCollective/Sovryn-smart-contracts/blob/development/contracts/connectors/loantoken/Pausable.sol

and used at:

    https://github.com/DistributedCollective/Sovryn-smart-contracts/blob/development/contracts/connectors/loantoken/LoanTokenLogicStandard.sol#L57

  pausable(msg.sig)

**Comment by computerphysicslab** [comment]
Actually bZx code comes with a pausable functionality not on contract level, but on function level.

**Comment by computerphysicslab** [comment]
Next steps:

1.- Modify State and Proxy contract to get global protocol pausable

2.- and on module level as well.

3.- Modify bZx Pausable and Proxy contract to get pausable functions w/o using the modifier nor the explicit checker on every function.

**Comment by computerphysicslab** [comment]
I have been testing the pausable contract with three levels of granurality but it is not yet clear how to deal with one of them, the protocol case. So, by now, in my local branch, loanToken can be paused and resumed with module or function granurality. But...

When trying to pause loanToken, feeSharingProxy functions (withdraw and transferToken) are still operative.

When trying to pause loanTokenV2, marginTrade function is still operative.
    The reason why is because the _checkPause() is only applied on the Proxy when delegating calls. marginTrade seems to be not using any proxy.

I think we need to reconsider the whole strategy, where to check if a function is paused or not. At proxy when delegating calls, at functions in their contracts, ... or hybrid approach, some at proxy, some others on their function implementation...

**Comment by computerphysicslab** [comment]
I think I have found a good implementation for the pausable contract:

Setting the pause check on proxy contract allow us to stop all functions of a contract in one shot. But there are at least 3 different proxies working simultaneously: loantoken, staking and protocol as far as I know.

One option would be to call 3 emergency pause transactions from exchequer multisig.

But another option is to use one beacon for the 3 proxies that tells them about the pause status. This way we achieve the global emergency panic button with just 1 call.

The beacon is an external source of information for proxies eip-1967. We can set pausable contract as the proxy beacon for checking the pausable status.

This would imply to merge the pausable task with the eip-1967 task into just one.

https://eips.ethereum.org/EIPS/eip-1967#beacons

Pausable contract could be a stand-alone instance that stores the pause status (global, modular or functional). Proxy contract would need the address of Pausable instance on deployment and would check its status on every delegatedcall.

Non-proxy contracts that should be pausable, would also require to get the address of the pausable instance on deployment and would check its status on every function.

**Comment by computerphysicslab** [comment]
Tyrone says proxies won't be upgraded...

Considering proxies won't be redeployed, I need a new approach:

Just upgrading logic, a check will be required on every function susceptible to be paused.

Pausable contract instance can store the flags for the pause status (at global/module/function level).

Current function-level pause (bZx) works for delegatedcalls, just on proxies.
OpenZeppelin pause works at contract level (module level) with inherintence, and global level as a global beacon instance.

To get the three levels of pausability on no-proxy contracts, current strategy is good (a global flag plus a module flag w/ a mapping), but will require to add the bZx equivalent for proxys on function level pausability, i.e. a mapping flag indexed on function selector or signature.

One problem might be selector clashes, when two contracts have two functions w/ same name and arguments (maybe withdraw, deposit, mint, burn... are very common function names).

So, maybe the function level should take into account not just the selector but also the module/contract name or instance address.

**Comment by ororopickpocket** [comment]
```when two contracts have two functions w/ same name and arguments```
In that case one overrides the other.

It will be enough to simply add a function toggleFreeze(bool freeze) (or similar) to emergency freeze the complete protocol.
can be added to the protocol settings.

**Comment by ororopickpocket** [comment]
it's rather unlikely that we'll need to pause all the independent contracts at once.

**Comment by computerphysicslab** [comment]
Ok. By adding a function toggleFreeze(bool freeze) to the protocol settings we could toggle a boolean flag (frozen/paused or not status) on State contract, right? I guess we need to add checker function and call it on every contract and function susceptible to be paused like this:

require (ProtocolSettings.isFrozen(), "Protocol is frozen");

Just to confirm the setup to pause the protocol. This approach's granularity is for pausing the entire protocol or nothing. A finer granularity would require a selector/contract mapping flag.
