### ISSUE TITLE
EIP-1967 pattern for loan tokens

### ISSUE THREAD

**Issue by tjcloa** [DistributedCollective/Sovryn-smart-contracts#211]
connectors/loantoken in Sovryn-smart-contracts repo implement proxy and logic, and they share storage layout. Consider utilising EIP-1967 pattern to decouple proxy and logic contracts

**Comment by computerphysicslab** [comment]
Starting point, branch development
    git pull
    New local branch Proxy-EIP-1967
    // git push --set-upstream origin Proxy-EIP-1967

1.- On Proxy contract: 
    1a.- The storage slot 0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc (obtained as bytes32(uint256(keccak256('eip1967.proxy.implementation')) - 1)) should hold the address of the logic contract that the proxy delegates to.
    
    1b.- Changes to this slot should be notified by the event: event Upgraded(address indexed implementation); It only changes on constructor, because Proxy is not upgradable.

2.- On UpgradableProxy contract:
    2a.- The storage slot 0xb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103 (obtained as bytes32(uint256(keccak256('eip1967.proxy.admin')) - 1)) should hold the address that is allowed to upgrade the logic contract address for the proxy.
    
    2b.- Changes to this slot should be notified by the event: event AdminChanged(address previousAdmin, address newAdmin);

    2c.- Changes to the implementation address slot should be notified by the event: event Upgraded(address indexed implementation);

**Comment by computerphysicslab** [comment]
Note: OpenZeppelin is using other different slots at https://github.com/OpenZeppelin/openzeppelin-sdk/blob/dc9e4ed/packages/lib/contracts/upgradeability/BaseUpgradeabilityProxy.sol :
keccak-256 hash of "org.zeppelinos.proxy.implementation"
bytes32 internal constant IMPLEMENTATION_SLOT = 0x7050c9e0f4ca769c69bd3a8ef740bc37934f8e2c036e5a723fd8ee048ed3f8c3;

**Comment by computerphysicslab** [comment]
Task completed. Code and tests upgraded. https://github.com/DistributedCollective/Sovryn-smart-contracts/compare/ca0db35f1e7d%5E...cdcc25936fea

**Comment by tjcloa** [comment]
we ain't going to deploy it unless redeploy completely
