### ISSUE TITLE
Babelfish genesis FISH sale

### ISSUE THREAD

**Issue by tjcloa** [DistributedCollective/Sovryn-smart-contracts#247]
"this has the highest priority
use genesis sale platform for babelfish FISH token genesis sale on sovryn
https://github.com/DistributedCollective/Genesis-Sale as a boilerplate
Vesting contract:
https://github.com/DistributedCollective/Sovryn-smart-contracts/tree/a8c02c08efcc404785ba68906ca89fe9d1e14251/contracts/governance/Vesting
Extended SIP description:
https://docs.google.com/document/d/1maErdhoPhb2GYU_Ts39bKxAeLLm8l8Kh7Vc0CG_Eqw4/edit
-----------------------------------------------------------------

We're going to use the same schema as with cSOV: 
cFISH will be an intermediary token which is a subject of sale and then cFISH will exchange it to FISH staking via Vesting contracts (locking with linear release during 10 months with 4 weeks period)
10 months will be 4 weeks x 10 = 280 days with linear unlocking every 28 days
Here are the details:

A. Sale Round 1 - 

Supply - 11,508,000
Vesting - 10 months linear (meaning the buyer will get 10% of the bought supply every month for the following 10 months after the sale)
Price in sats - decided 1 week ahead of the sale
Duration - up to 48 hours unless the supply is fully sold ahead of the deadline

B. Sale Round 2 - 

Supply - 20,000,000
Vesting - 
a. 50% unlocked immediately 
b. 50% vested linear for 10 months

e.g. If I buy 100 FISH during this round I get 50FISH unlocked immediately and then on a monthly basis for the next 10 months, I get 1/10 of the remaining 50 tokens

Price in sats - decided 1 week ahead of the first round
Duration - up to 48 hours unless the supply is fully sold ahead of the deadline

**Comment by powerhousefrank** [comment]
This is being done by me in the Repo: https://github.com/DistributedCollective/origins
