### ISSUE TITLE
A MARGIN POSITION IS OPENED AND FUNDS DISAPEARED

### ISSUE THREAD

**Issue by jjmr007** [DistributedCollective/Sovryn-smart-contracts#251]
A user [opened a 3x long margin position](https://explorer.rsk.co/tx/0x25037312531b37d768f026535e3cf2e121f765b9f6c54da9a1f6ef27103c8820?__ctab=Transaction) in rBTC supplying 0.004142278020000000 rBTC,

But when you query the status if his loan Id: 0x8f10e5e886d6122dc3cec3fd35f7997eb13396b203f655b5aaaed6e1814c26e3
the collateral that should be of  around 0.1242 WRBTC, it is just 0.000274722955733825 WRBTC, by the moment  write this the marging transaction was the latest of the [users account](https://explorer.rsk.co/address/0x0084607fffa62eae449ceea975bb9710ada455c2) and the transaction was with a msg.value matcing exactly with the collateral value: 0.00414227802 rBTC, and the balance of this address is just: 0.00004057542 rBTC

¿WHERE THE MONEY WENT?

the getPastEvents method for:
* Liquidate
* CloseWithDeposit
* CloseWithSwap

related to this LoanId are all giving back empty arrays.

I'm tagging this as an urgent bug. If it is regarded later as less relevant I'll change the status.

This is the [ticket](https://sovryn.freshdesk.com/a/tickets/272).
![CaptureLiquidationPrice](https://user-images.githubusercontent.com/17028457/119918553-ab6b3080-bf36-11eb-9aa1-15bc583d8721.png)

**Comment by ororopickpocket** [comment]
you've got access to the admin panel, julio. there you would have seen 5 liquidations

**Comment by jjmr007** [comment]
Thank you Orora
