### ISSUE TITLE
Enable swaps fee sharing with SOV stakers

### ISSUE THREAD

**Issue by tjcloa** [DistributedCollective/Sovryn-smart-contracts#271]
The usage of the protocol (SwapsExternal.sol) for all swaps on sovryn. 
Currently, SOV stakers are not gaining any fees on swaps, but just the LPs. 
By making the calls via the SwapsExternal, stakers would gain a trading fee as well.
this requires the divergence check built into this method (should be on the divergence check branch)

**Comment by smbsp** [comment]
Analysis: https://docs.google.com/document/d/19oHdgL_VIRmQrP2pfmx5vtm3zXQpHQbiLf_nFRQtlX4/edit?usp=sharing

**Comment by smbsp** [comment]
Tests completed: https://github.com/DistributedCollective/Sovryn-smart-contracts/commit/58fe4d8b30bb62b6c1bf62b6438f0d4008832b2a

**Comment by smbsp** [comment]
The changes are merged to development.

Branch: https://github.com/DistributedCollective/Sovryn-smart-contracts/tree/merged-dev-slippage-rebates
Reference PR: https://github.com/DistributedCollective/Sovryn-smart-contracts/pull/342
